name: BedrockTransferPacketCommand
version: ${project.version}
main: com.github.camotoy.bedrocktransferpacketcommand.spigot.BedrockTransferPacketCommandSpigot
api-version: 1.16
authors: [ Camotoy ]
depend:
  - Geyser-Spigot
